### ISSUE TITLE
Install BeautifulSoup

### ISSUE THREAD

**Issue by chapuawe** [eudemonics/cloudget#1]
Hi, I have seen your code and in the readme you say "to install BeautifulSoup you put: pip install BeautifulSoup" since since your code does not connect directly to the BeautifulSoup module you have to install it like this: pip install bs4. Regards :) PS: sorry but I do not speak English

**Comment by eudemonics** [comment]
it's been awhile since i worked on it but I'm pretty sure it is because the code is using bs3 not bs4, and some of the functions will result in error if you import the wrong version. i may have updated to bs4 in a later version but i haven't pushed it to github yet.
